feat(connections): Implement connection API with native query
web-slate/linkedin-clone-api pull request #49
Opened 2022-05-12 07:50 UTC by jpukg

## Issue ID
NA
## Summary
Implement connection API with native query
## Steps to implement this feature

## Checklist

- [ ] Have you added the summary of what your changes do and why you'd like us to include them?
- [ ] Have you added the steps to implement this feature?
- [x] Have the files been linted and formatted?
- [ ] Have the docs been updated to match the changes in the PR?
- [ ] Have the tests been updated to match the changes in the PR?
- [ ] Have you run the tests locally to confirm they pass?

### What is the need for this tech update, and the steps to reproduce the issue?

### What is the current status?

### How does this PR fix the problem, Screenshot Please?

2022-05-15 14:18 UTC, ramsunvtech requested changes

2022-05-15 14:18 UTC, ramsunvtech commented on src/main/java/com/linkedin/network/api/ConnectionController.java
> +		}
@jpukg, can this be replaced without inverse condition?

```
if (CollectionUtils.isEmpty(connections)) {
    apiResponse.setStatus(HttpStatus.OK.toString()); // update status code
    apiResponse.setMessage("No active connections available");
} else {
    apiResponse.setResponse(connections);
    apiResponse.setStatus(HttpStatus.OK.toString());
    apiResponse.setMessage("Found Connections");
}
  return ResponseEntity.ok().body(apiResponse);
```

2022-05-15 14:18 UTC, ramsunvtech commented on src/main/java/com/linkedin/network/service/impl/ConnectionServiceImpl.java
> +	}
can this be auto wired. i mean this look like boilerplate code. correct me here

2022-05-15 17:45 UTC, jpukg commented on src/main/java/com/linkedin/network/api/ConnectionController.java
> +		}
@ramsunvtech will be given as a task to you guys.

2022-05-15 17:46 UTC, jpukg commented on src/main/java/com/linkedin/network/service/impl/ConnectionServiceImpl.java
> +	}
@ramsunvtech yes, this will be corrected by you guys.

2022-05-16 12:20 UTC, ramsunvtech commented
@jpukg please share the working screenshot and DB tables and update the postman collection

2022-05-18 15:37 UTC, shangan23 commented on src/main/java/com/linkedin/network/api/ConnectionController.java
> +		}
what is the inverse condition?

2022-05-24 07:31 UTC, jpukg commented
![image](https://user-images.githubusercontent.com/4453880/169974275-4d502a24-9a8b-483e-bb1a-ea12f3728d4d.png)

2024-01-10 19:56 UTC, closed without merging