tech(get/experience): add experience mapper
web-slate/linkedin-clone-api pull request #51
Opened 2022-05-16 13:13 UTC by ramsunvtech

## Issue ID
NA

## Summary
Able to find experience by user id after change experience Mapper

## Steps to do this Tech Update

## Checklist

- [X] Have you added the summary of what your changes do and why you'd like us to include them?
- [ ] Have you added the steps you followed?
- [ ] Have the files been linted and formatted?
- [ ] Have the docs been updated to match the changes in the PR?
- [ ] Have the tests been updated to match the changes in the PR?
- [ ] Have you run the tests locally to confirm they pass?

### What is the need for this tech update, and the steps to reproduce the issue?
Mainly to remove boiler plate for manual getter and setter code to transfer values from one instance to another.
 
### What is the current status?
API working as expected after technical update

### How does this PR fix the problem, Screenshot Please?

#### Found Experience

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/1652629/164351791-d7e49096-ee96-4137-afb4-9d895f9250c7.png">

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/1652629/164351826-b280e986-1c37-4778-a16d-6e02cd28741d.png">

#### Experience is not exist

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/1652629/164351872-c8c6be3e-bb35-497f-8444-7a75456a208b.png">

2022-05-16 13:28 UTC, jpukg requested changes

2022-05-16 13:28 UTC, jpukg commented on src/main/java/com/linkedin/network/service/impl/ExperienceServiceImpl.java
> +    public Experience updateExperienceByExperienceId(ExperienceDTO experienceRequest) {
You should use Mapper here.

2022-05-16 13:28 UTC, jpukg commented on src/main/java/com/linkedin/network/service/impl/ExperienceServiceImpl.java
>          Experience experiencePayload = new Experience();
You should use Mapper here as well.

2022-05-16 13:28 UTC, jpukg commented on src/main/java/com/linkedin/network/service/impl/ExperienceServiceImpl.java
> +        List<Experience> experiences = experienceRepository.findByUserId(userId);
Put it in a single statement.

2022-05-16 13:28 UTC, jpukg commented on src/main/java/com/linkedin/network/mapper/ExperienceMapper.java
> +    @Mapping(source = "experienceId", target = "experienceId")
Why you defined same target?. This is again a duplicate. Please change.

2022-05-16 13:28 UTC, jpukg commented on src/main/java/com/linkedin/network/api/ExperienceController.java
>                  apiResponse.setResponse(foundExperience);
Please use constructor here instead of setting value using setters.

2022-05-18 15:35 UTC, shangan23 requested changes
LGTM other than JP's comment

2025-10-03 09:30 UTC, closed without merging